// @ts-nocheck -- skip type checking
import * as docs_9 from "../content/docs/getting-started/prereqs.mdx?collection=docs&hash=1777681872532"
import * as docs_8 from "../content/docs/getting-started/local.mdx?collection=docs&hash=1777681872532"
import * as docs_7 from "../content/docs/getting-started/index.mdx?collection=docs&hash=1777681872532"
import * as docs_6 from "../content/docs/getting-started/fin.mdx?collection=docs&hash=1777681872532"
import * as docs_5 from "../content/docs/getting-started/env.mdx?collection=docs&hash=1777681872532"
import * as docs_4 from "../content/docs/getting-started/deploy-backend.mdx?collection=docs&hash=1777681872532"
import * as docs_3 from "../content/docs/getting-started/deploy-app.mdx?collection=docs&hash=1777681872532"
import * as docs_2 from "../content/docs/getting-started/billing.mdx?collection=docs&hash=1777681872532"
import * as docs_1 from "../content/docs/getting-started/auth.mdx?collection=docs&hash=1777681872532"
import * as docs_0 from "../content/docs/index.mdx?collection=docs&hash=1777681872532"
import { _runtime } from "fumadocs-mdx"
import * as _source from "../source.config"
export const docs = _runtime.docs<typeof _source.docs>([{ info: {"path":"index.mdx","absolutePath":"/Users/shawn/.t3/worktrees/start-faster/t3code-5701012f/apps/docs/content/docs/index.mdx"}, data: docs_0 }, { info: {"path":"getting-started/auth.mdx","absolutePath":"/Users/shawn/.t3/worktrees/start-faster/t3code-5701012f/apps/docs/content/docs/getting-started/auth.mdx"}, data: docs_1 }, { info: {"path":"getting-started/billing.mdx","absolutePath":"/Users/shawn/.t3/worktrees/start-faster/t3code-5701012f/apps/docs/content/docs/getting-started/billing.mdx"}, data: docs_2 }, { info: {"path":"getting-started/deploy-app.mdx","absolutePath":"/Users/shawn/.t3/worktrees/start-faster/t3code-5701012f/apps/docs/content/docs/getting-started/deploy-app.mdx"}, data: docs_3 }, { info: {"path":"getting-started/deploy-backend.mdx","absolutePath":"/Users/shawn/.t3/worktrees/start-faster/t3code-5701012f/apps/docs/content/docs/getting-started/deploy-backend.mdx"}, data: docs_4 }, { info: {"path":"getting-started/env.mdx","absolutePath":"/Users/shawn/.t3/worktrees/start-faster/t3code-5701012f/apps/docs/content/docs/getting-started/env.mdx"}, data: docs_5 }, { info: {"path":"getting-started/fin.mdx","absolutePath":"/Users/shawn/.t3/worktrees/start-faster/t3code-5701012f/apps/docs/content/docs/getting-started/fin.mdx"}, data: docs_6 }, { info: {"path":"getting-started/index.mdx","absolutePath":"/Users/shawn/.t3/worktrees/start-faster/t3code-5701012f/apps/docs/content/docs/getting-started/index.mdx"}, data: docs_7 }, { info: {"path":"getting-started/local.mdx","absolutePath":"/Users/shawn/.t3/worktrees/start-faster/t3code-5701012f/apps/docs/content/docs/getting-started/local.mdx"}, data: docs_8 }, { info: {"path":"getting-started/prereqs.mdx","absolutePath":"/Users/shawn/.t3/worktrees/start-faster/t3code-5701012f/apps/docs/content/docs/getting-started/prereqs.mdx"}, data: docs_9 }], [{"info":{"path":"getting-started/meta.json","absolutePath":"/Users/shawn/.t3/worktrees/start-faster/t3code-5701012f/apps/docs/content/docs/getting-started/meta.json"},"data":{"pages":["prereqs","local","deploy-app","deploy-backend","env","auth","billing","fin"]}}])