/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as CallbackRouteImport } from './app/callback'
import { Route as AuthenticatedRouteImport } from './app/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './app/_authenticated/index'
import { Route as AuthenticatedAuthorizedRouteImport } from './app/_authenticated/_authorized'
import { Route as AuthenticatedAuthorizedFilesRouteImport } from './app/_authenticated/_authorized/files'
import { Route as AuthenticatedAuthorizedDashboardRouteImport } from './app/_authenticated/_authorized/dashboard'
import { Route as AuthenticatedAuthorizedAccountRouteImport } from './app/_authenticated/_authorized/account'
import { Route as AuthenticatedAuthorizedPagesIndexRouteImport } from './app/_authenticated/_authorized/pages.index'
import { Route as AuthenticatedAuthorizedPagesPageIdRouteImport } from './app/_authenticated/_authorized/pages.$pageId'

const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuthorizedRoute = AuthenticatedAuthorizedRouteImport.update({
  id: '/_authorized',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuthorizedFilesRoute =
  AuthenticatedAuthorizedFilesRouteImport.update({
    id: '/files',
    path: '/files',
    getParentRoute: () => AuthenticatedAuthorizedRoute,
  } as any)
const AuthenticatedAuthorizedDashboardRoute =
  AuthenticatedAuthorizedDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAuthorizedRoute,
  } as any)
const AuthenticatedAuthorizedAccountRoute =
  AuthenticatedAuthorizedAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedAuthorizedRoute,
  } as any)
const AuthenticatedAuthorizedPagesIndexRoute =
  AuthenticatedAuthorizedPagesIndexRouteImport.update({
    id: '/pages/',
    path: '/pages/',
    getParentRoute: () => AuthenticatedAuthorizedRoute,
  } as any)
const AuthenticatedAuthorizedPagesPageIdRoute =
  AuthenticatedAuthorizedPagesPageIdRouteImport.update({
    id: '/pages/$pageId',
    path: '/pages/$pageId',
    getParentRoute: () => AuthenticatedAuthorizedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/callback': typeof CallbackRoute
  '/account': typeof AuthenticatedAuthorizedAccountRoute
  '/dashboard': typeof AuthenticatedAuthorizedDashboardRoute
  '/files': typeof AuthenticatedAuthorizedFilesRoute
  '/pages/$pageId': typeof AuthenticatedAuthorizedPagesPageIdRoute
  '/pages/': typeof AuthenticatedAuthorizedPagesIndexRoute
}
export interface FileRoutesByTo {
  '/callback': typeof CallbackRoute
  '/': typeof AuthenticatedIndexRoute
  '/account': typeof AuthenticatedAuthorizedAccountRoute
  '/dashboard': typeof AuthenticatedAuthorizedDashboardRoute
  '/files': typeof AuthenticatedAuthorizedFilesRoute
  '/pages/$pageId': typeof AuthenticatedAuthorizedPagesPageIdRoute
  '/pages': typeof AuthenticatedAuthorizedPagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/callback': typeof CallbackRoute
  '/_authenticated/_authorized': typeof AuthenticatedAuthorizedRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/_authorized/account': typeof AuthenticatedAuthorizedAccountRoute
  '/_authenticated/_authorized/dashboard': typeof AuthenticatedAuthorizedDashboardRoute
  '/_authenticated/_authorized/files': typeof AuthenticatedAuthorizedFilesRoute
  '/_authenticated/_authorized/pages/$pageId': typeof AuthenticatedAuthorizedPagesPageIdRoute
  '/_authenticated/_authorized/pages/': typeof AuthenticatedAuthorizedPagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/account'
    | '/dashboard'
    | '/files'
    | '/pages/$pageId'
    | '/pages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/callback'
    | '/'
    | '/account'
    | '/dashboard'
    | '/files'
    | '/pages/$pageId'
    | '/pages'
  id:
    | '__root__'
    | '/_authenticated'
    | '/callback'
    | '/_authenticated/_authorized'
    | '/_authenticated/'
    | '/_authenticated/_authorized/account'
    | '/_authenticated/_authorized/dashboard'
    | '/_authenticated/_authorized/files'
    | '/_authenticated/_authorized/pages/$pageId'
    | '/_authenticated/_authorized/pages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CallbackRoute: typeof CallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_authorized': {
      id: '/_authenticated/_authorized'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAuthorizedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_authorized/files': {
      id: '/_authenticated/_authorized/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof AuthenticatedAuthorizedFilesRouteImport
      parentRoute: typeof AuthenticatedAuthorizedRoute
    }
    '/_authenticated/_authorized/dashboard': {
      id: '/_authenticated/_authorized/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedAuthorizedDashboardRouteImport
      parentRoute: typeof AuthenticatedAuthorizedRoute
    }
    '/_authenticated/_authorized/account': {
      id: '/_authenticated/_authorized/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAuthorizedAccountRouteImport
      parentRoute: typeof AuthenticatedAuthorizedRoute
    }
    '/_authenticated/_authorized/pages/': {
      id: '/_authenticated/_authorized/pages/'
      path: '/pages'
      fullPath: '/pages/'
      preLoaderRoute: typeof AuthenticatedAuthorizedPagesIndexRouteImport
      parentRoute: typeof AuthenticatedAuthorizedRoute
    }
    '/_authenticated/_authorized/pages/$pageId': {
      id: '/_authenticated/_authorized/pages/$pageId'
      path: '/pages/$pageId'
      fullPath: '/pages/$pageId'
      preLoaderRoute: typeof AuthenticatedAuthorizedPagesPageIdRouteImport
      parentRoute: typeof AuthenticatedAuthorizedRoute
    }
  }
}

interface AuthenticatedAuthorizedRouteChildren {
  AuthenticatedAuthorizedAccountRoute: typeof AuthenticatedAuthorizedAccountRoute
  AuthenticatedAuthorizedDashboardRoute: typeof AuthenticatedAuthorizedDashboardRoute
  AuthenticatedAuthorizedFilesRoute: typeof AuthenticatedAuthorizedFilesRoute
  AuthenticatedAuthorizedPagesPageIdRoute: typeof AuthenticatedAuthorizedPagesPageIdRoute
  AuthenticatedAuthorizedPagesIndexRoute: typeof AuthenticatedAuthorizedPagesIndexRoute
}

const AuthenticatedAuthorizedRouteChildren: AuthenticatedAuthorizedRouteChildren =
  {
    AuthenticatedAuthorizedAccountRoute: AuthenticatedAuthorizedAccountRoute,
    AuthenticatedAuthorizedDashboardRoute:
      AuthenticatedAuthorizedDashboardRoute,
    AuthenticatedAuthorizedFilesRoute: AuthenticatedAuthorizedFilesRoute,
    AuthenticatedAuthorizedPagesPageIdRoute:
      AuthenticatedAuthorizedPagesPageIdRoute,
    AuthenticatedAuthorizedPagesIndexRoute:
      AuthenticatedAuthorizedPagesIndexRoute,
  }

const AuthenticatedAuthorizedRouteWithChildren =
  AuthenticatedAuthorizedRoute._addFileChildren(
    AuthenticatedAuthorizedRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAuthorizedRoute: typeof AuthenticatedAuthorizedRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAuthorizedRoute: AuthenticatedAuthorizedRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CallbackRoute: CallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
